### PR TITLE
use oss.s.o maven repository in order to get sync to central

### PR DESCRIPTION
**Pull request by brianm**
Pull request to make POM changes needed to deploy to oss.sonatype.org which will sync to maven central.

See the [singup docs](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-2.Signup) for the final steps to get perms to push, etc.

### CODE REVIEW

**Comment by jeluard** [comment]
Nice! I would also be interested to see artifacts pushed to the central repo.

I am not sure it will be feasible yet as central repo has a strict policy for groupId, namely ensuring they map to a valid domain owned by the project (more [details](https://docs.sonatype.org/display/Repository/Choosing+your+Coordinates)).

Changing the groupId to something like `com.github.sbtourist` would do it.

**Comment by sbtourist** [comment]
Hey guys,

Sorry for this late response, for some reason Github didn't send me any notification.

I'll apply this ASAP.

**Comment by sbtourist** [comment]
Guys,

Here's the ticket to get Journal.IO into Sonatype: https://issues.sonatype.org/browse/OSSRH-5261
I had to change the groupid  to com.github.sbtourist, as suggested by Julien.
Hopefully they'll create the repository soon.

**Comment by jeluard** [comment]
Nice, thanks!

**Pull request merged**
